---
date: "March 2024"

format:
  cv-html: default
  # cv-pdf: default
---

# Jonathan Jayes

<div class="contact-info">

- {{< fa map-marker-alt >}} Carl Bernlunds Gata 13, 222 20 Lund, Sweden
- {{< fa phone-alt >}} +27 838 64 71 90, +46 724 03 81 26
- {{< fa envelope >}} [j0nathanjayes@gmail.com](mailto:j0nathanjayes@gmail.com)
- {{< fa globe >}} [www.interludeone.com](http://www.interludeone.com)
- {{< fa brands linkedin >}} [jonathanjayes](https://www.linkedin.com/in/jonathanjayes)
- {{< fa brands github >}} [j-jayes](https://github.com/j-jayes)

</div>

Economic historian and data scientist researching technological change and electrification at Lund University. Currently studying towards a PhD in Economic History.

## Experience

### Codera Analytics (Remote)
**Data Scientist**  
*December 2022–Present*  
Working as part of their experienced team of quantitative economists and data scientists. Involved in the automated collection of macroeconomic and ESG data and the visualization of trends in provincial revenue and expenditure.

### Fathom Data (Remote)
**Junior Data Scientist**  
*January 2022–March 2022*  
Worked part-time creating automated reports in Rmarkdown for the commercialization of a data product on consumer prices. [Knowledge sharing session on producing code that writes its own code.](https://interludeone.com/posts/2022-03-04-programmatically-generate-tabs-in-rmarkdown/programmatically-generate-tabs-in-rmarkdown.html)

### University of California, Berkeley
**Quantitative Analyst, Research Assistant to Prof. Barry Eichengreen**  
*June 2020–February 2021*  
Collected data and conducted NLP analysis on reports by the select committee on the Gold Standard in South Africa in 1933. Work resulted in a research paper entitled "Gold and South Africa’s Great Depression".

## Education

### PhD in Economic History
**Lund University, School of Economics and Management**  
*2021-2025*  
Supervised by Prof. Kerstin Enflo. Thesis examines the winners and losers from the technological change that occurred with electrification in the first half of the 20th century.

### Master's in Economics (cum laude)
**Stellenbosch University**  
*2020–2021*  
Researcher for the Laboratory for the Economics of Africa's Past. Submitted a research project entitled "A Century Later: Lessons from the Spanish Flu Pandemic of 1918".

## Publications

- Fourie and Jayes (2021). "Health inequality and the 1918 Spanish flu in South Africa". World Development Special Issue: Pandemics, COVID19, and Sustainability and Development. [10.1016/j.worlddev.2021.105407](https://www.sciencedirect.com/science/article/abs/pii/S0305750X2100019X)

## Technical Skills

- Full stack data scientist skilled in data scraping, cleaning, visualization, and machine learning.
- **Software:** Python, R, SQLite, OpenAI API, Google Cloud Functions, GitHub Actions.
- **Languages:** Native English speaker, intermediate Swedish, beginner French.

## Interests

- Home brewing tasty pale ales.
- Running, with twelve half marathons and two full marathons completed.


